### ISSUE TITLE
Odd number of columns

### ISSUE THREAD

**Issue by mirimCZ** [eperezcosano/hexagonal-grid#1]
Hi,

there is a bug if it ends up rendering odd number of columns - to reproduce just try `<canvas id="canvas" width="1048" height="1048"/>` in your codepen.

Otherwise great job, many thanks :)

**Comment by eperezcosano** [comment]
Thanks for letting me know, i will try to fix it as soon as i can :)

**Comment by Geniusflip** [comment]
For future travelers - I ended up solving this by adding the offset height back on every odd loop

Like so: 
```javascript
 for (let y = radius; y + radius * Math.sin(angle) < height; y += radius * Math.sin(angle)) {
        let j = 1;
        for (let x = radius - gutter; x + radius * (1 + Math.cos(angle)) < width; x += radius * (1 + Math.cos(angle)), y += (-1) ** j * radius * Math.sin(angle)) {
            j++ 
            drawHexagon(canvas, ctx, x, y)
        }
        y += j % 2 *radius * Math.sin(angle);
      }
```

**Comment by eperezcosano** [comment]
Changes added. Thanks!
